project:
  type: website

website:
  title: "H-blocker ðŸ§ª From Lab with Light"
  description: "Let's make things stronger!"
  logo: logo.png
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Notebook"
        href: posts/index.qmd

format:
  html:
    theme: cosmo
    css: styles.css
